language: node_js # Building with node js
node_js:
   - stable # Download the stable node version
 
# Blocklist
branches:
   except:
     - gh-pages # will be deployed to, no need to build it
 
cache:
  directories:
   - node_modules
 
script:
   - npm install
   - npm run build --prod # Generates the dist folder with built angular app
 
deploy:
   - provider: pages
     skip_cleanup: true # Prevent travis from cleaning out the branch before the deploy occurs
     github_token: $GITHUB_TOKEN_TEST # Set in travis-ci.org dashboard
     on:
         branch: master # Build only from master
     local_dir: ./dist/deploy/ #
   - provider: azure_web_apps
     username: myappdeploy\$myappdeploy
     password: ijxjwiMBXlLodJcskNDxAdpbLnSoKXWP1hJ1Dxa9ky8fLj38kqHlLeiMua34
     site: https://myappdeploy.azurewebsites.net
     on:
         branch: master